name-template: 'v$NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES 

  ## Why kube-dialer
  A single page web application with shortcuts (external links) genearted from ConfigMap

  ## Installation
  Download artifact and unzip it.

  With Helm 3 run

  ```bash
  helm install --namespace kube-dialer kube-dialer deploy/charts/dialer
  ```

  ## Docker images
  - docker pull docker.pkg.github.com/kruzio/kube-dialer/dialer:master
