name-template: 'v$NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🚀 Highlights'
    labels:
      - 'release/highlight'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'release/breaking-change'      
  - title: 'Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES 

  For full changes, see the [comparison between $PREVIOUS_TAG and v$NEXT_MINOR_VERSION](https://github.com/theme-next/hexo-theme-next/compare/$PREVIOUS_TAG...v$NEXT_MINOR_VERSION)

  ## Why kube-dialer
  A single page web application with shortcuts (external links) genearted from ConfigMap

  ## Installation
  Download artifact and unzip it.

  With Helm 3 run

  ```bash
  helm install --namespace kube-dialer kube-dialer deploy/charts/dialer
  ```

  ## Docker images
  - docker pull docker.pkg.github.com/kruzio/kube-dialer/dialer:$NEXT_PATCH_VERSION