apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedialer-{{ .Release.Name }}
  labels:
    app: kube-dialer
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kruz.io/component.role: kube-dialer
    kruz.io/component.tier: edge-kube-dialer
    kruz.io/info.vendor: Kruz IO Inc.
spec:
  selector:
    matchLabels:
      app: kube-dialer
  replicas: {{default 1 .Values.replicas}}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-dialer
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
    spec:
      volumes:
      # The static assets
      - name: static
        emptyDir: {}      
      # Map all keys to files.
      - name: dialer-config
        configMap:
          name: dialer-config
      - name: dialer-tiles
        configMap:
          name: dialer-tiles       

      # Pod Security
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 1000
      initContainers:
      - name: dialer-staticdata
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        command: [ "sh" ]
        args: [ "-c", "cp -r /www/* /static && cp /config/config.toml /static/"]
        volumeMounts:
        - name: dialer-config
          mountPath: /config
        - name: static
          mountPath: /static    


      containers:
      - name: dialer
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}   
        #Container Security            
        securityContext:     
            allowPrivilegeEscalation: false
            capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
        command: [ "hugo" ]
        args: [ "server", "--bind", "0.0.0.0", "-p", "{{ .Values.dialerPort }}","-s", "/static", "--log", "--verboseLog"]
        volumeMounts:
        - name: static
          mountPath: /static
        - name: dialer-tiles
          mountPath: /static/content/tiles          
        ports:
        - name: http
          containerPort: {{ .Values.dialerPort }}
          protocol: TCP 