---
name: Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      # - name: Launch Cluster
      #   uses: helm/kind-action@v1.0.0
      #   with:
      #     version: v0.9.0
      #     cluster_name: iskan
      #     node_image: kindest/node:v1.19.1
      #     wait: 5m

      - name: Build & Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KRUZIO_DOCKER_HUB_TOKEN: ${{ secrets.KRUZIO_DOCKER_HUB_TOKEN }}
        run: |
          docker login --username kruzops --password=$KRUZIO_DOCKER_HUB_TOKEN
          make get-release-bins
          make gorelease